"use client";
import { ChangeEvent, DragEvent, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Download, FileSpreadsheet, Image as ImageIcon, Plus, Presentation, Save, Settings, Trash2, Upload } from "lucide-react";
import { deduplicatePromotions, isStrongDeal, parsePromotions } from "@/lib/parser";
import { sampleFolder } from "@/lib/sample";
import { loadFolders, saveFolder } from "@/lib/storage";
import { animalCategories, emptyPromotion, promotionTypes, type AnimalCategory, type Folder, type PdfPage, type Promotion, type Settings as AppSettings } from "@/lib/types";

const labels:Record<string,string>={Cat:"Kat",Dog:"Hond","Rabbit and rodents":"Konijnen en knaagdieren",Bird:"Vogels",Fish:"Vissen",Accessories:"Accessoires","Maxi Deals":"Maxi Deals","Maxi Zoo Friends":"Maxi Zoo Friends",Outlet:"Outlet","Percentage discount":"Procentkorting","Multi-buy":"Meeneemactie","Free item":"Gratis artikel","Fixed price":"Vaste prijs","Friends price":"Friends-aanbieding","Maxi Deal":"Maxi Deal",Other:"Overig"};
const colors:Record<AnimalCategory,string>={Cat:"#8b4298",Dog:"#df651b","Rabbit and rodents":"#679b36",Bird:"#d5a400",Fish:"#2289ad",Accessories:"#377d76","Maxi Deals":"#00613a","Maxi Zoo Friends":"#7c9e2e",Outlet:"#e3a51d"};
const defaultSettings:AppSettings={compact:true,showImages:true,showNotes:true,highlightStrongDeals:true,autoCrop:true,columns:2,minConfidence:.6};
type TextAnchor={page:number;text:string;x:number;y:number;width:number;height:number;pageWidth:number;pageHeight:number};
const normalize=(value:string)=>value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
function locateProduct(p:Promotion,anchors:TextAnchor[]){const words=normalize(`${p.brand} ${p.productName}`).split(" ").filter(w=>w.length>3);let best:{anchor:TextAnchor;score:number}|undefined;for(const anchor of anchors.filter(a=>a.page===p.sourcePage)){const text=normalize(anchor.text);const score=words.filter(w=>text.includes(w)).length;if(!best||score>best.score)best={anchor,score};}if(!best||best.score<Math.min(2,Math.max(1,words.length)))return undefined;const a=best.anchor,width=Math.min(a.pageWidth*.46,Math.max(260,a.width+a.pageWidth*.24)),height=Math.min(a.pageHeight*.3,Math.max(220,a.height+a.pageHeight*.2));return {x:Math.max(0,Math.min(a.pageWidth-width,a.x-a.pageWidth*.18)),y:Math.max(0,Math.min(a.pageHeight-height,a.y-a.pageHeight*.14)),width,height,pageWidth:a.pageWidth,pageHeight:a.pageHeight};}

function compare(current:Promotion[],previous:Promotion[]):Promotion[]{const old=new Map(previous.map(p=>[`${p.brand}|${p.productName}`.toLowerCase(),p]));const next:Promotion[]=current.map(p=>{const match=old.get(`${p.brand}|${p.productName}`.toLowerCase());const changeStatus:Promotion["changeStatus"]=!match?"new":match.promotionText!==p.promotionText||match.promotionalPrice!==p.promotionalPrice?"changed":"unchanged";return {...p,changeStatus};});for(const p of previous){if(!current.some(c=>`${c.brand}|${c.productName}`.toLowerCase()===`${p.brand}|${p.productName}`.toLowerCase()))next.push({...p,id:`expired-${p.id}`,changeStatus:"expired"});}return next;}
async function crop(page:PdfPage,p:Promotion){return new Promise<string>((resolve,reject)=>{const image=new Image();image.onload=()=>{const b=p.sourceBounds||{x:0,y:0,width:page.width/2,height:page.height/2,pageWidth:page.width,pageHeight:page.height};const canvas=document.createElement("canvas");canvas.width=640;canvas.height=420;const ctx=canvas.getContext("2d")!;ctx.fillStyle="white";ctx.fillRect(0,0,640,420);const scale=Math.min(640/b.width,420/b.height);ctx.drawImage(image,b.x,b.y,b.width,b.height,(640-b.width*scale)/2,(420-b.height*scale)/2,b.width*scale,b.height*scale);resolve(canvas.toDataURL("image/jpeg",.9));};image.onerror=reject;image.src=page.image;});}

export default function App(){
 const [folder,setFolder]=useState<Folder>(sampleFolder),[history,setHistory]=useState<Folder[]>([]),[busy,setBusy]=useState(""),[error,setError]=useState(""),[advanced,setAdvanced]=useState(false),[settings,setSettings]=useState(defaultSettings),[category,setCategory]=useState("Alle"),[type,setType]=useState("Alle"),[selected,setSelected]=useState<string|null>(null);const sheetRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{loadFolders().then(setHistory).catch(()=>setError("Eerdere folders konden niet worden geladen."));},[]);
 const visible=useMemo(()=>folder.promotions.filter(p=>(category==="Alle"||p.animalCategory===category)&&(type==="Alle"||p.promotionType===type)&&p.confidence>=settings.minConfidence),[folder.promotions,category,type,settings.minConfidence]);
 const previewPages=useMemo(()=>{const active=visible.filter(p=>p.changeStatus!=="expired"),chunks:Promotion[][]=[];for(let i=0;i<active.length;i+=8)chunks.push(active.slice(i,i+8));return (chunks.length?chunks:[[]]).map(items=>animalCategories.map(c=>[c,items.filter(p=>p.animalCategory===c)] as const).filter(([,promos])=>promos.length));},[visible]);
 function patch(id:string,values:Partial<Promotion>){setFolder(f=>({...f,promotions:f.promotions.map(p=>p.id===id?{...p,...values}:p)}));}
 async function readPdf(file:File){setBusy("PDF-pagina's verwerken...");setError("");try{const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/build/pdf.worker.min.mjs",import.meta.url).toString();const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const pages:PdfPage[]=[];const anchors:TextAnchor[]=[];let all="";for(let n=1;n<=pdf.numPages;n++){setBusy(`Pagina ${n} van ${pdf.numPages} verwerken...`);const page=await pdf.getPage(n),content=await page.getTextContent(),viewport=page.getViewport({scale:1.5});const text=content.items.map(item=>("str" in item?item.str:"")).join("  ");for(const item of content.items){if(!("str" in item)||!item.str.trim()||!("transform" in item))continue;const point=viewport.convertToViewportPoint(item.transform[4],item.transform[5]);anchors.push({page:n,text:item.str,x:point[0],y:point[1],width:("width" in item?item.width:0)*1.5,height:Math.max(12,Math.abs(item.transform[3])*1.5),pageWidth:viewport.width,pageHeight:viewport.height});}all+=`\n--- PAGE ${n} ---\n${text}`;const canvas=document.createElement("canvas");canvas.width=Math.floor(viewport.width);canvas.height=Math.floor(viewport.height);await page.render({canvasContext:canvas.getContext("2d")!,viewport}).promise;pages.push({pageNumber:n,image:canvas.toDataURL("image/jpeg",.88),width:canvas.width,height:canvas.height,text});}let promotions=deduplicatePromotions(parsePromotions(all));try{const response=await fetch("/api/parse",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text:all,localPromotions:promotions})});if(response.ok)promotions=(await response.json()).promotions;}catch{}if(settings.autoCrop)promotions=await Promise.all(promotions.map(async p=>{const page=pages[p.sourcePage-1],sourceBounds=locateProduct(p,anchors);if(!page||!sourceBounds)return {...p,productImage:"",validationWarnings:[...p.validationWarnings,"Geen betrouwbare productfoto gevonden; controleer of vervang het beeld."]};return {...p,sourceBounds,productImage:await crop(page,{...p,sourceBounds}),validationWarnings:[...p.validationWarnings,"Automatische productuitsnede: controle vereist."]};}));setFolder({id:crypto.randomUUID(),name:file.name,importedAt:new Date().toISOString(),period:"",pages,promotions});}catch(e){console.error(e);setError("De PDF kon niet worden verwerkt. Controleer of het een geldige Maxi Zoo-folder is.");}finally{setBusy("");}}
 function drop(event:DragEvent){event.preventDefault();const file=event.dataTransfer.files[0];if(file?.type==="application/pdf")void readPdf(file);else setError("Sleep een PDF-bestand van een Belgische Maxi Zoo-folder hierheen.");}
 async function persist(){await saveFolder(folder);setHistory(await loadFolders());setBusy("Folder lokaal bewaard");setTimeout(()=>setBusy(""),1500);}
 function useComparison(id:string){const previous=history.find(f=>f.id===id);if(previous)setFolder(f=>({...f,promotions:compare(f.promotions,previous.promotions)}));}
 async function replaceImage(id:string,e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>patch(id,{productImage:String(reader.result)});reader.readAsDataURL(file);}
 async function recrop(p:Promotion){const page=folder.pages[p.sourcePage-1];if(page)patch(p.id,{productImage:await crop(page,p)});}
 async function pageCanvases(){if(!sheetRef.current)throw new Error("Geen voorbeeld beschikbaar");const html2canvas=(await import("html2canvas")).default;return Promise.all([...sheetRef.current.querySelectorAll<HTMLElement>(".sheet")].map(page=>html2canvas(page,{scale:3,backgroundColor:"#fff",useCORS:true})));}
 async function png(){try{const pages=await pageCanvases(),gap=36,width=Math.max(...pages.map(c=>c.width)),height=pages.reduce((sum,c)=>sum+c.height,0)+gap*(pages.length-1),combined=document.createElement("canvas");combined.width=width;combined.height=height;const context=combined.getContext("2d")!;context.fillStyle="white";context.fillRect(0,0,width,height);let y=0;for(const page of pages){context.drawImage(page,0,y);y+=page.height+gap;}const a=document.createElement("a");a.href=combined.toDataURL("image/png");a.download="maxi-zoo-cheat-sheet.png";a.click();}catch{setError("De PNG-export is mislukt.");}}
 async function pdf(){try{const pages=await pageCanvases(),{jsPDF}=await import("jspdf"),doc=new jsPDF("p","mm","a4");pages.forEach((page,index)=>{if(index)doc.addPage("a4","p");doc.addImage(page.toDataURL("image/png"),"PNG",0,0,210,297);});doc.save("maxi-zoo-cheat-sheet.pdf");}catch{setError("De PDF-export is mislukt.");}}
 async function pptx(){try{const pages=await pageCanvases(),mod=await import("pptxgenjs"),Pptx=(mod as typeof mod&{default:typeof mod.default}).default,ppt=new Pptx();ppt.defineLayout({name:"A4",width:8.2677,height:11.6929});ppt.layout="A4";pages.forEach(page=>{const slide=ppt.addSlide();slide.addImage({data:page.toDataURL("image/png"),x:0,y:0,w:8.2677,h:11.6929});});await ppt.writeFile({fileName:"maxi-zoo-cheat-sheet.pptx"});}catch{setError("De PowerPoint-export is mislukt.");}}
 async function excel(){try{const ExcelJS=(await import("exceljs")).default,book=new ExcelJS.Workbook(),sheet=book.addWorksheet("Promoties");sheet.columns=Object.keys(folder.promotions[0]||emptyPromotion()).filter(k=>!['productImage','sourceBounds'].includes(k)).map(k=>({header:k,key:k,width:22}));folder.promotions.forEach(p=>sheet.addRow(p));sheet.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};sheet.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF00613A"}};const blob=new Blob([await book.xlsx.writeBuffer()]);const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="maxi-zoo-promoties.xlsx";a.click();URL.revokeObjectURL(a.href);}catch{setError("De Excel-export is mislukt.");}}
 return <main><header><div><span className="eyebrow">INTERNE TOOL · MAXI ZOO BELGIË</span><h1>Cheat Sheet Generator</h1><p>Van Belgische promotiefolder naar een gecontroleerd winkeloverzicht.</p></div><button className="headerButton" onClick={()=>setAdvanced(v=>!v)}><Settings size={18}/>Geavanceerde Maxi Zoo-modus</button></header>
 {advanced&&<section className="settings"><b>Geavanceerde instellingen</b><label><input type="checkbox" checked={settings.compact} onChange={e=>setSettings(s=>({...s,compact:e.target.checked}))}/>Compacte A4-weergave</label><label><input type="checkbox" checked={settings.showImages} onChange={e=>setSettings(s=>({...s,showImages:e.target.checked}))}/>Productbeelden tonen</label><label><input type="checkbox" checked={settings.highlightStrongDeals} onChange={e=>setSettings(s=>({...s,highlightStrongDeals:e.target.checked}))}/>Sterke deals markeren</label><label>Kolommen <select value={settings.columns} onChange={e=>setSettings(s=>({...s,columns:Number(e.target.value) as 1|2}))}><option value="1">1</option><option value="2">2</option></select></label><label>Minimumzekerheid {Math.round(settings.minConfidence*100)}% <input type="range" min="0" max="1" step=".05" value={settings.minConfidence} onChange={e=>setSettings(s=>({...s,minConfidence:Number(e.target.value)}))}/></label></section>}
 <section className="toolbar"><button onClick={()=>setFolder(sampleFolder)}>Demomodus</button><button onClick={()=>setFolder(f=>({...f,promotions:[...f.promotions,emptyPromotion()]}))}><Plus size={16}/>Promotie toevoegen</button><button onClick={persist}><Save size={16}/>Lokaal bewaren</button><select defaultValue="" onChange={e=>useComparison(e.target.value)}><option value="">Vergelijk met vorige folder...</option>{history.filter(f=>f.id!==folder.id).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><span className="spacer"/><button onClick={png}><Download size={16}/>PNG</button><button onClick={pdf}><Download size={16}/>PDF</button><button onClick={pptx}><Presentation size={16}/>PowerPoint</button><button onClick={excel}><FileSpreadsheet size={16}/>Excel</button></section>
 {error&&<div className="error"><AlertTriangle size={18}/>{error}<button onClick={()=>setError("")}>Sluiten</button></div>}{busy&&<div className="notice">{busy}</div>}
 <section className="upload" onDragOver={e=>e.preventDefault()} onDrop={drop}><Upload size={28}/><b>Sleep een Maxi Zoo-folder in PDF-formaat hierheen</b><span>of</span><label>PDF kiezen<input hidden type="file" accept="application/pdf" onChange={e=>e.target.files?.[0]&&readPdf(e.target.files[0])}/></label></section>
 {folder.pages.length>0&&<section><h2>Folderpagina's</h2><div className="pages">{folder.pages.map(p=><button key={p.pageNumber} onClick={()=>document.getElementById(`page-${p.pageNumber}`)?.scrollIntoView()}><img src={p.image} alt={`Folderpagina ${p.pageNumber}`}/><span>Pagina {p.pageNumber}</span></button>)}</div></section>}
 <section className="filters"><b>{folder.promotions.length} promoties</b><label>Categorie <select value={category} onChange={e=>setCategory(e.target.value)}><option>Alle</option>{animalCategories.map(c=><option key={c} value={c}>{labels[c]}</option>)}</select></label><label>Promotietype <select value={type} onChange={e=>setType(e.target.value)}><option>Alle</option>{promotionTypes.map(t=><option key={t} value={t}>{labels[t]}</option>)}</select></label></section>
 <div className="workspace"><section className="tableWrap"><table><thead><tr><th>Beeld</th><th>Product</th><th>Categorie</th><th>Promotie</th><th>Prijzen</th><th>Geldig</th><th>Controle</th><th/></tr></thead><tbody>{visible.map(p=><tr key={p.id} className={p.validationWarnings.length?"warn":""}><td>{p.productImage?<img className="thumb" src={p.productImage} alt=""/>:<ImageIcon/>}<label className="smallButton">Vervang<input hidden type="file" accept="image/*" onChange={e=>replaceImage(p.id,e)}/></label><button className="smallButton" onClick={()=>setSelected(selected===p.id?null:p.id)}>Uitsnede</button></td><td><input value={p.brand} placeholder="Merk" onChange={e=>patch(p.id,{brand:e.target.value})}/><input value={p.productName} onChange={e=>patch(p.id,{productName:e.target.value})}/><textarea value={p.description} placeholder="Beschrijving" onChange={e=>patch(p.id,{description:e.target.value})}/></td><td><select value={p.animalCategory} onChange={e=>patch(p.id,{animalCategory:e.target.value as AnimalCategory})}>{animalCategories.map(c=><option value={c} key={c}>{labels[c]}</option>)}</select><select value={p.promotionType} onChange={e=>patch(p.id,{promotionType:e.target.value as Promotion["promotionType"]})}>{promotionTypes.map(t=><option value={t} key={t}>{labels[t]}</option>)}</select></td><td><input value={p.promotionText} onChange={e=>patch(p.id,{promotionText:e.target.value})}/><label><input type="checkbox" checked={p.isFriendsOffer} onChange={e=>patch(p.id,{isFriendsOffer:e.target.checked})}/>Friends</label><label><input type="checkbox" checked={p.isPickAndMix} onChange={e=>patch(p.id,{isPickAndMix:e.target.checked})}/>Mix & match</label></td><td><input value={p.normalPrice} placeholder="Normaal" onChange={e=>patch(p.id,{normalPrice:e.target.value})}/><input value={p.promotionalPrice} placeholder="Promo" onChange={e=>patch(p.id,{promotionalPrice:e.target.value})}/><input value={p.unitPrice} placeholder="Eenheidsprijs" onChange={e=>patch(p.id,{unitPrice:e.target.value})}/></td><td><input type="date" value={p.validFrom} onChange={e=>patch(p.id,{validFrom:e.target.value})}/><input type="date" value={p.validUntil} onChange={e=>patch(p.id,{validUntil:e.target.value})}/><small>Bron p. {p.sourcePage}</small></td><td><span className={`confidence ${p.confidence<.7?"low":""}`}>{Math.round(p.confidence*100)}%</span>{p.changeStatus&&<span className={`change ${p.changeStatus}`}>{({new:"Nieuw",changed:"Gewijzigd",expired:"Verlopen",unchanged:"Ongewijzigd"})[p.changeStatus]}</span>}{p.validationWarnings.map(w=><small className="warningText" key={w}>{w}</small>)}</td><td><button aria-label="Verwijder promotie" onClick={()=>setFolder(f=>({...f,promotions:f.promotions.filter(x=>x.id!==p.id)}))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></section>
 <section className="preview"><h2>Smartphone- en A4-voorbeeld</h2><div className="sheetPages" ref={sheetRef}>{previewPages.map((groups,pageIndex)=><div className={`sheet ${settings.compact?"compact":""}`} style={{"--columns":settings.columns} as React.CSSProperties} key={pageIndex}><div className="sheetHeader"><span>INTERNE CHEAT SHEET</span><h2>MAXI ZOO PROMOTIES</h2><p>{folder.period||folder.name}<small>Pagina {pageIndex+1} van {previewPages.length}</small></p></div><div className="sheetGrid">{groups.map(([c,ps])=><section key={c} style={{"--category":colors[c]} as React.CSSProperties}><h3>{labels[c]}</h3>{ps.map(p=><article key={p.id} className={settings.highlightStrongDeals&&isStrongDeal(p)?"strong":""}>{settings.showImages&&<div>{p.productImage?<img src={p.productImage} alt=""/>:<ImageIcon/>}</div>}<p><b>{p.brand}</b> {p.productName}{settings.showNotes&&p.notes&&<small>{p.notes}</small>}</p><strong>{p.promotionText}<small>{p.promotionalPrice}</small></strong></article>)}</section>)}</div><footer>Interne werkhulp - Controleer altijd de voorwaarden en deelnemende referenties in de Belgische Maxi Zoo-folder.</footer></div>)}</div></section></div>
 {selected&&(()=>{const p=folder.promotions.find(x=>x.id===selected);if(!p)return null;const page=folder.pages[p.sourcePage-1];return <div className="modal"><div><h2>Uitsnede corrigeren</h2>{page&&<img src={page.image} alt="Bronpagina"/>}<div className="cropFields">{(["x","y","width","height"] as const).map(k=><label key={k}>{k}<input type="number" value={p.sourceBounds?.[k]??(k==="width"?page?.width/2:k==="height"?page?.height/2:0)} onChange={e=>patch(p.id,{sourceBounds:{x:p.sourceBounds?.x||0,y:p.sourceBounds?.y||0,width:p.sourceBounds?.width||page?.width/2||100,height:p.sourceBounds?.height||page?.height/2||100,pageWidth:page?.width||1,pageHeight:page?.height||1,[k]:Number(e.target.value)}})}/></label>)}</div><button onClick={()=>recrop(p)}>Uitsnede toepassen</button><button onClick={()=>setSelected(null)}>Sluiten</button></div></div>})()}</main>;
}

